name: Run JPF

on:
  push:

jobs:
  run-jpf:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'

    - name: Clone jpf-core
      run: |
        git clone https://github.com/javapathfinder/jpf-core.git /tmp/jpf-core
        cd /tmp/jpf-core
        ./gradlew buildJars

    - name: Compile JPF sources related
      run: |
        mkdir -p facade/bin
        find abstract-factory/src/main/java/ -name "*.java" | xargs javac -d abstract-factory/bin -cp /tmp/jpf-core/build/jpf-classes.jar --enable-preview --release 11

    - name: Run JPF on Module
      run: |
        cat abstract-factory/example.jpf
        echo "JPF: abstract-factory/example.jpf"
        java -jar /tmp/jpf-core/build/RunJPF.jar abstract-factory/example.jpf --enable-preview
